plugins {
    id 'com.android.application'
}

android {
    namespace "com.micklab.reversy"
    compileSdk 36

    defaultConfig {
        applicationId "com.micklab.reversy"
        minSdk 24
        targetSdk 36
        def githubRunNumber = System.getenv("GITHUB_RUN_NUMBER") ?: "1"
        versionCode Integer.parseInt(githubRunNumber)
        versionName "1.${githubRunNumber}"
    }

    signingConfigs {
        release {
            storeFile file("release.keystore")
            storePassword System.getenv("KEYSTORE_PASSWORD")
            keyAlias System.getenv("KEY_ALIAS")
            keyPassword System.getenv("KEY_PASSWORD")
        }
    }

    buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.release
        }
    }
}

dependencies {
}
